### ISSUE TITLE
This library is AMAZING!

### ISSUE THREAD

**Issue by crearo** [marcorei/Infinite-Fire#6]
I'm sorry I'm putting this up as an issue, but I couldn't find a way to thank you.
This is the cleanest implementation of using recyclerview and firebase together. I read the code and it was simply beautiful; the working example was extremely helpful. It was an extreme hassle getting firebase to load paginated results, and this library manages this perfectly.

Thank you very, very much @marcorei

**Comment by marcorei** [comment]
Thank you. I'm happy to see that this library was helpful to you!
