### ISSUE TITLE
Adding null items to The array to Integrated Ads

### ISSUE THREAD

**Issue by 3llomi** [marcorei/Infinite-Fire#7]
Hi,
how can i Add a null items to the **InfiniteFireArray** so i can integrate Ads in RecyclerView.
for example i want to check in the **getItemViewType**
`if (snapshots.getItem(position).getValue() == null){
return VIEW_TYPE_AD_VIEW
}`

Thanks for this Great Library

**Comment by marcorei** [comment]
Hey, thanks!

Good question. One idea that just came to mind is to [override `getItemCount()`](https://github.com/marcorei/Infinite-Fire/blob/master/infinitefire/src/main/java/com/marcorei/infinitefire/InfiniteFireRecyclerViewAdapter.java#L86) and to [modify `getItemViewType()`](https://github.com/marcorei/Infinite-Fire/blob/master/app/src/main/java/com/marcorei/infinitefiredemo/ui/activity/InfiniteRecyclerViewLinearActivity.java#L224) when extending the `InfiniteFireRecyclerViewAdapter`.

Let's say you want to display an ad every 15 entries. You could override `getItemCount()` like so
```Java
@Override
public int getItemCount() {
    int numberOfAds = Math.floor(snapshots.getCount() / 14);
    return super.getItemCount() + numberOfAds;
}
```

And implement `getItemViewType()` like so
```Java
@Override
public int getItemViewType(int position) {
    if(position == 0) {
        return VIEW_TYPE_HEADER;
    }
    else if(position == getItemCount() - 1) {
        return VIEW_TYPE_FOOTER;
    }
    // Added check for the ad!
    else if(((position - indexOffset) % 15) == 14) {
        return VIEW_TYPE_AD; 
    }
    return VIEW_TYPE_CONTENT;
}
```

I had no time to test this but I think that could work!

**Comment by 3llomi** [comment]
@marcorei Thanks man,but after that it's just deleting the **Content item**  every **15** items and replace it with an **ad Item** and when i scroll to the end of the List it throws an error `java.lang.IndexOutOfBoundsException` 

any suggestions please?

**Comment by marcorei** [comment]
Sure. It sounds like you did not yet adjust `onBindViewHolder()`. When you call `snapshots.getItem()` in `onBindViewHolder()` you have to modify the `position`. The `position` in the `RecyclerView` is not the same as in the `snapshots` array. 

In the example app the position is offset by the amount of header items: `Chat chat = snapshots.getItem(position - indexOffset).getValue();` – now you have to also add the amount of ads that are inserted before that item.

**Comment by 3llomi** [comment]
@marcorei i am sorry,but i didn't get that .
do i have to add the **Amount of ads** in `OnBindViewHolder` like this or what?
`Chat chat = snapshots.getItem(position - indexOffset+ amountOfAds ).getValue();`
can you clarify it for me with an Example please?

**Comment by marcorei** [comment]
Alright. 
- Let's say you got **31** chat messages loaded into `snapshots` and 
- you want that every **5th** item in the RecyclerView is an ad.
- So after every **4th** chat message in `snapshots` your Adapter has to add one extra item to your RecyclerView where you can display the ad later on. (You do that in `getItemCount()`) 
- In this case your Adapter would add **7** new items that do not exist in the `snapshots` array.

Depending on your position in the RecyclerView the number of additional items which the Adapter has added before your current position varies. For example:

- Lets say the current `position` in the RecyclerView is **12**. 
- You got **1** header, so normally the chat message which the Adapter would select from `snapshots` would be at index **11**.
- BUT you've got ads. Every **5th** item is an ad. That means: in addition to the header, the adapter at that position also has added **2** additional items, which are not chat messages and not represented in `snapshots`.
- Therefore the actual position of the chat message in `snapshots` is at index **9**

So when you have to select the correct chat message from `snapshots` in `onBindViewHolder()` you want to calculate the number of ads depending on the current position, e.g. like this
```Java
int numberOfAdsBeforeCurrentPosition = (int) Math.floor((position - indexOffset) / 5);
Chat chat = snapshots.getItem(position - indexOffset - numberOfAdsBeforeCurrentPosition).getValue();
```

**Comment by macxtor** [comment]
I've managed to get it work by following method.
Lets say you wanna print ad after every 6th item in recyclerview.  To get it done I've added following code in **infinitefirearray.java** onChildAdded : 
`   if((i+1)%6==0)
                        {
                            dataSnapshots.add(i, dataSnapshot);
                            notifyOnChangedListener(OnChangedListener.EventType.Added, i);
                            i= getIndexForKey(previousChild);
                        }`


If you need more help let me know.

**Comment by marcorei** [comment]
I think this is solved. I'll close this one.
